services:
  postgres:
    image: postgres
    container_name: postgres_db
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 2004
        POSTGRES_DB: chat-app-db
        PG_DATA: /var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'  # Run in desktop mode
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: unless-stopped
volumes:
  postgres:
  pgadmin: