spring:
  application:
    name: like-button
  datasource:
    url: jdbc:postgresql://localhost:5432/chat-app-db
    username: postgres
    password: 2004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# server running port
server:
  port: 8080
